---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: source
  namespace: cert-manager
spec:
  secretName: source-tls
  commonName: yourdns.com
  dnsNames:
    - yourdns.com
    - "*.yourdns.com"
  issuerRef:
    name: letsencrypt
    kind: Issuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "argocd,demo,main,dev,openstack" # Control auto-reflection namespaces