apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-load-definition"
type: Opaque
stringData:
  load_definition.json: |-
    {
      "users": [
        {
          "name": "{{ .Values.auth.username }}",
          "password": "{{ .Values.auth.password }}",
          "tags": "administrator"
        }
      ],
      "permissions": [
        {
          "user": "{{ .Values.auth.username }}",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "policies": [
        {
          "name": "ha-all",
          "pattern": ".*",
          "vhost": "/",
          "definition": {
            "ha-mode": "all",
            "ha-sync-mode": "automatic",
            "ha-sync-batch-size": 1
          }
        },
        {
          "vhost": "/",
          "name": "iot.sensordata-ha",
          "pattern": "^iot.sensordata$",
          "definition": {            
            "message-ttl": 300000,
            "max-length" : 2000,            
            "dead-letter-exchange": "DLX.iot.sensordata.fanout",
            "ha-mode": "all",
            "ha-sync-mode": "automatic",
            "ha-sync-batch-size": 1
          },
          "priority": 1,
          "apply-to": "queues"
        },
        {
          "vhost": "/",
          "name": "iot.sensordata_DLQ-ha",
          "pattern": "^iot.sensordata_DLQ$",
          "definition": {
            "message-ttl": 300000,
            "max-length-bytes": 2000,
            "dead-letter-exchange": "DLX.iot.sensordata.REQ.fanout",
            "ha-mode": "all",
            "ha-sync-mode": "automatic",
            "ha-sync-batch-size": 1
          },
          "priority": 1,
          "apply-to": "queues"
        }
      ],
      "exchanges": [
        {
          "name": "iot.mqtt.fanout",
          "vhost": "/",
          "type": "fanout",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        },
        {
          "name": "DLX.iot.sensordata.fanout",
          "vhost": "/",
          "type": "fanout",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        },
        {
          "name": "DLX.iot.sensordata.REQ.fanout",
          "vhost": "/",
          "type": "fanout",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        }
      ],
      "bindings": [
        {
          "source": "iot.mqtt.topic",
          "vhost": "/",
          "destination": "iot.sensordata",
          "destination_type": "queue",
          "routing_key": "",
          "arguments": {}
        },
        {
          "source": "DLX.iot.sensordata.fanout",
          "vhost": "/",
          "destination": "iot.sensordata_DLQ",
          "destination_type": "queue",
          "routing_key": "",
          "arguments": {}
        },
        {
          "source": "DLX.iot.sensordata.REQ.fanout",
          "vhost": "/",
          "destination": "iot.sensordata",
          "destination_type": "queue",
          "routing_key": "",
          "arguments": {}
        }
      ],
      "queues": [
        {
          "name": "iot.sensordata",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {}
        },
        {
          "name": "iot.sensordata_DLQ",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {}
        }
      ]
    }